// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestionPlatform2.Models;

#nullable disable

namespace QuestionPlatform2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130234947_mig2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuestionPlatform2.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("QuestionPlatform2.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "İçerik 1",
                            CreatedAt = new DateTime(2025, 12, 1, 2, 49, 47, 631, DateTimeKind.Local).AddTicks(7815),
                            IsActive = true,
                            Title = "Soru Başlığı 1",
                            UpdatedAt = new DateTime(2025, 12, 1, 2, 49, 47, 631, DateTimeKind.Local).AddTicks(7832)
                        },
                        new
                        {
                            Id = 2,
                            Content = "İçerik 2",
                            CreatedAt = new DateTime(2025, 12, 1, 2, 49, 47, 631, DateTimeKind.Local).AddTicks(7835),
                            IsActive = true,
                            Title = "Soru Başlığı 2",
                            UpdatedAt = new DateTime(2025, 12, 1, 2, 49, 47, 631, DateTimeKind.Local).AddTicks(7836)
                        },
                        new
                        {
                            Id = 3,
                            Content = "İçerik 3",
                            CreatedAt = new DateTime(2025, 12, 1, 2, 49, 47, 631, DateTimeKind.Local).AddTicks(7838),
                            IsActive = false,
                            Title = "Soru Başlığı 3",
                            UpdatedAt = new DateTime(2025, 12, 1, 2, 49, 47, 631, DateTimeKind.Local).AddTicks(7838)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
