// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestionPlatform2.Models;

#nullable disable

namespace QuestionPlatform2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuestionPlatform2.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerContent = "Üye olmak için sağ üstteki 'Kayıt Ol' butonuna tıklayın.",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(952),
                            QuestionId = 1,
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(953)
                        },
                        new
                        {
                            Id = 2,
                            AnswerContent = "Şifre sıfırlama sayfasından e-posta adresinizi girerek yeni şifre oluşturabilirsiniz.",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(956),
                            QuestionId = 2,
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(957)
                        },
                        new
                        {
                            Id = 3,
                            AnswerContent = "Evet, tüm veriler SSL ile şifrelenir ve gizliliğiniz korunur.",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(959),
                            QuestionId = 3,
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(960)
                        },
                        new
                        {
                            Id = 4,
                            AnswerContent = "Profil ayarlarından istediğiniz değişiklikleri yapabilirsiniz.",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(962),
                            QuestionId = 4,
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(963)
                        },
                        new
                        {
                            Id = 5,
                            AnswerContent = "Müşteri hizmetleri ile iletişime geçebilirsiniz.",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(965),
                            QuestionId = 5,
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(966)
                        });
                });

            modelBuilder.Entity("QuestionPlatform2.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("QuestionPlatform2.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "İçerik 1",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(722),
                            IsActive = true,
                            Title = "Soru Başlığı 1",
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(723)
                        },
                        new
                        {
                            Id = 2,
                            Content = "İçerik 2",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(727),
                            IsActive = true,
                            Title = "Soru Başlığı 2",
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(728)
                        },
                        new
                        {
                            Id = 3,
                            Content = "İçerik 3",
                            CreatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(731),
                            IsActive = false,
                            Title = "Soru Başlığı 3",
                            UpdatedAt = new DateTime(2025, 12, 8, 4, 13, 10, 63, DateTimeKind.Local).AddTicks(731)
                        });
                });

            modelBuilder.Entity("QuestionPlatform2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuestionPlatform2.Models.Answer", b =>
                {
                    b.HasOne("QuestionPlatform2.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestionPlatform2.Models.Favorite", b =>
                {
                    b.HasOne("QuestionPlatform2.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionPlatform2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestionPlatform2.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
